server:
  port: 8081
  servlet:
    context-path: /devices

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/iot_devices}
    username: ${SPRING_DATASOURCE_USERNAME:andrei}
    password: ${SPRING_DATASOURCE_PASSWORD:andrei}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

jwt:
  secret-key: 2a6c4356f908d52b8b634b5129f89e1b93b7b648d8e4d69c8e8bdaffb8672e4d

logging:
  level:
    org.springframework.kafka: INFO
    org.springframework.security: DEBUG