server:
  port: 8081
  servlet:
    context-path: /devices

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/iot_devices
    username: andrei
    password: andrei
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  security:
    jwt:
      secret-key: 2a6c4356f908d52b8b634b5129f89e1b93b7b648d8e4d69c8e8bdaffb8672e4d
